//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMFRelation
    {
        public int Id { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<int> MID { get; set; }
        public Nullable<int> FID { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Firm Firm { get; set; }
        public virtual Team Team { get; set; }
    }
}
