//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int id { get; set; }
        public string Type { get; set; }
        public string Heading { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> Published { get; set; }
        public Nullable<int> FirmID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual Firm Firm { get; set; }
        public virtual Team Team { get; set; }
    }
}
